volumes:
  sql:

networks:
  back:

services:
  mysql:
    image: mysql:8.0
    container_name: bdd
    volumes:
      - sql:/var/lib/mysql
    networks:
      - back
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=superheroes
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=admin
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 2
  java:
    image: ds
    build: ./java
    container_name: backend
    networks:
      - back
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://bdd:3306/superheroes
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - 8448:8448
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "localhost:8448"]
      interval: 10s
      timeout: 5s
      retries: 3
  angular:
    image: dsfront
    build: ./angular
    container_name: frontend
    environment:
      - BACKEND_URL_ENV_VAR=http://localhost:8448
    ports:
      - 80:80
    depends_on:
      java:
          condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "localhost:80" ]
      interval: 5s
      timeout: 5s
      retries: 2